exports.apis = {
    'login_admin': '/a/b/c/d/e/f/admin/login',



    'admin_update_profile': '/users/update',
    'admin_update_phone_number': '/users/ChangePhoneNumber',
    'admin_update_password': '/users/changePassword',
    'admin_update_username': '/users/changeusername',
    'admin_pay_user': 'admin/users/pay/',

    'admin_get_credit':'users/get/credit',
    'admin_pay_credit':'users/credit/pay',
    'admin_get_salary':'admin/users/salary',
    'admin_get_my_profile': '/users/profile',

    'admin_create_category': '/admin/category/store',
    'admin_get_category': '/admin/category/',
    'admin_search_category': '/admin/category/search',
    'admin_update_category': '/admin/category/update/',
    'admin_delete_category': '/admin/category/delete/',

"admin_search_category_expense":'/admin/category/expense/search',
"admin_get_category_expense":'/admin/category/expense/',
"admin_delete_category_expense":'/admin/category/expense/delete/',
"admin_update_category_expense":'/admin/category/expense/update/',
"admin_create_category_expense":'/admin/category/expense/store',
'admin_filter_expense':'/admin/expense/filter/',

    'admin_create_bank': '/admin/bank/store',
    'admin_get_bank': '/admin/bank/',
    'admin_search_bank': '/admin/bank/search',
    'admin_update_bank': '/admin/bank/update/',
    'admin_delete_bank': '/admin/bank/delete/',

    'admin_create_expense': '/admin/expense/store',
    'admin_get_expense': '/admin/expense/',
    'admin_update_expense': '/admin/expense/update/',
    'admin_delete_expense': '/admin/expense/delete/',
    

    'admin_create_menu_category': '/admin/menu/category/store',
    'admin_get_menu_category': '/admin/menu/category/',
    'admin_search_menu_category': '/admin/menu/category/search',
    'admin_update_menu_category': '/admin/menu/category/update/',
    'admin_delete_menu_category': '/admin/menu/category/delete/',

    'admin_create_totalcash': '/admin/totalcash/store',
    'admin_get_totalcash': '/admin/totalcash/',
    'admin_search_totalcash': '/admin/totalcash/search',
    'admin_update_totalcash': '/admin/totalcash/update/',
    'admin_delete_totalcash': '/admin/totalcash/delete/',



    'admin_create_menu': '/admin/menu/store',
    'admin_get_menu': '/admin/menu/',
    'admin_get_menu_for_linking': '/admin/menu/from/store',
    'admin_search_menu': '/admin/menu/search',
    'admin_update_menu': '/admin/menu/update/',
    'admin_delete_menu': '/admin/menu/delete/',
    'admin_payed_order':'/admin/casher/paye/',
    'admin_update_bank_user':'/admin/casher/bank/update',
    'admin_get_casher_reports':'/admin/casher/reports',
    'admin_get_waiter_reports':'/user/waiter/reports',
    'admin_given_casher_reports':'/admin/casher/given',
    'admin_given_waiter_reports':'/user/waiter/given',
    'admin_order':'/admin/casher/store',
    'admin_change_config':'/admin/casher/changeconfig',
    'admin_update_order':'/admin/casher/update',
    'admin_get_order':'/admin/casher/',
    'admin_un_flag_order':'/admin/casher/unflag/',
    'admin_flag_order':'/admin/casher/flag/',
    'admin_view_order':'/admin/casher/view/',
    'admin_get_flaged_order':'/admin/casher/flaged/orders/',
    'admin_get_all_flagged_orders':'/admin/casher/flaged/orders/all',
    'admin_get_all_payed_orders':'/admin/casher/payed/orders/all',
    'admin_get_all_flagged_Dorders':'/admin/casher/flaged/delivery/orders/all',
    'admin_get_all_payed_Dorders':'/admin/casher/payed/delivery/orders/all',

    'admin_get_all_transfered':'/admin/items/transfer/history/all',
    'admin_get_items_filtered':'/admin/items/transfer/history/data',
    'admin_transfer_item':'/admin/items/transfer/',
    'admin_item_link':'/admin/items/link/',
    'admin_item_unlink':'/admin/items/unlink/',
    'admin_create_item': '/admin/item/store',
    'admin_get_item': '/admin/item/',
    'admin_get_pagin_item': '/admin/item/web',
    'admin_get_for_filter_item': '/admin/item/for/filter/',
    'admin_search_item': '/admin/item/search',
    'admin_update_item': '/admin/item/update/',
    'admin_delete_item': '/admin/item/delete/',
    'admin_disable_item': '/admin/item/disable/',
    'admin_enable_item': '/admin/item/enable/',
    'admin_get_items_log': '/admin/items/log/',
    'admin_filter_items_log': '/admin/items/filter/log/',
    'admin_filter_items_transfered':'/admin/items/filter/transfered/',
    'admin_create_items': '/users/items/store',
    // 'admin_get_items': '/admin/items/in/branch/1',
    'admin_get_items': '/admin/items/',
    'admin_update_items': '/admin/items/update/',
    'admin_delete_items': '/admin/items/delete/',
    'admin_filter_items': '/admin/items/filter/',
    'admin_disable_items': '/admin/items/disable/',
    'admin_enable_items': '/admin/items/enable/',
    'admin_get_report_folder': '/admin/report/folder/get/all/',
    'admin_get_all_items_log': '/admin/items/log/get/all',
    'admin_get_all_report': '/admin/report/dashbored/all/',
    'admin_get_all_report_tiems_log': '/admin/items/log/get/all/report/',
    'admin_get_all_report_tiems_data': '/admin/items/log/get/all/report/data/',
    'admin_get_all_report_tiems_stock': '/admin/items/get/all/shop/report/',
    'admin_get_all_report_tiems_store': '/admin/items/get/all/store/report/',


    'admin_get_users': '/admin/users/',
    'admin_get_waiter_users': '/admin/users/waiter',
    'admin_get_chef_users':'/admin/users/chef',
    'admin_get_all_users': '/users/get/all',
    'admin_create_user': '/admin/users/register/',
    'admin_update_user': '/admin/users/update/',
    'admin_disable_user': '/admin/users/disable/',
    'admin_enable_user': '/admin/users/enable/',
    'admin_password_user': '/admin/users/change/password/',
    'admin_filter_user': '/admin/users/search',
    'admin_get_branch': '/admin/branches',
    'admin_delete_user': '/admin/users/delete/',
    'admin_reported': '/admin/report/reported',



    'admin_approve_item': '/admin/approve/',
    'users_get_item': '/users/item/get/',
    'users_seal_request_items': '/users/items/request/sell/',
    'users_request_items': '/users/request/store',
    'admin_items_requested_approve': '/users/request/approve/',
    'users_get_request_items': '/users/request/admin/',
    'users_get_request_items_detail': '/admin/requestd/items/',
    'admin_search_items_requested': '/users/request/search',
    'users_delete_request_items': '/users/request/delete/',
    'users_delte_folder_request_items': '/users/request/delete/folder/',
    'users_get_branch': '/users/branches',

    'admin_sell_items': '/admin/items/sell/',
    'users_get_for_filter_item': '/users/item/for/filter/',

    'users_transfer_items': '/admin/items/transfer/',
    'users_return_items': '/users/items/return/',
    'users_get_items': '/users/items/get/',
    'users_update_items': '/users/items/update/',
    'users_delete_items': '/users/items/delete/',
    'users_filter_items': '/users/items/filter/',
    'users_disable_items': '/users/items/disable/',
    'users_enable_items': '/users/items/enable/',
    'users_get_report': '/users/report/dashbored/',
    'users_get_report_casher':'/users/report/dashbored/casher/',
    'users_get_report_casher_graph':'/users/report/dashbored/casher/graph',
    'admin_get_report': '/admin/report/dashbored/',
    'admin_get_report_cahser':'/admin/report/dashbored/casher/',
    'admin_filter_date_casher_report_bank':'/admin/report/dashbored/casher/bank/',
    'admin_get_report_cahser_graph':'/admin/report/dashbored/casher/graph',
    'admin_filter_report': '/admin/report/by/filter/',
    'admin_filter_date_report': '/admin/report/by/date/',
    'admin_filter_date_casher_report': '/admin/report/casher/by/date/',
    'admin_get_reporttr': '/admin/report/transfer/return/',
    'admin_to_shope_items': '/users/items/transfer/to/shope/',
    'users_update_request_name': '/users/items/request/update/name/',

    'users_create_bank': '/users/bank/store',
    'users_get_bank': '/users/bank/',
    'users_update_bank': '/users/bank/update/',
    'users_delete_bank': '/users/bank/delete/',
    'admin_get_reportbnack': '/admin/report/bank/',
    'test_config': '/isconfig',

    'admin_get_order_chef':'/user/chef',
    'admin_create_remark':'/admin/users/remark/',
    'admin_get_order_chef_admin':'/user/chef/order/admin',
    'admin_view_order_chef':'/user/chef/view/',
    'admin_done_all_order':'/user/chef/done/all/',
    'admin_done_order':'/user/chef/done/',
    'admin_done_order_all':'/user/chef/done/all/',
    'admin_Grouped_order':'/user/chef/grouped',
    'admin_Grouped_order_done':'/user/chef/grouped/done',
    'admin_search_order':'/admin/casher/search',
    'admin_get_expense_export':'admin/report/export/expense/'



};